// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://reeeoursehkuvprnhkyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlZWVvdXJzZWhrdXZwcm5oa3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNDgxODAsImV4cCI6MjA3NDgyNDE4MH0.PLzG6XanOl0mDbQszjmM4eIh-KAK07txmvyb3ZWzZZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});